name: TypeScript Version Check and Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force new release even if versions match'
        required: false
        type: boolean
        default: false
  
jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Get current TypeScript version
        id: current-version
        run: |
          if [ -f "./BlazingTs/BlazingTs/tools/typescript/package.json" ]; then
            CURRENT_VERSION=$(cat ./BlazingTs/BlazingTs/tools/typescript/package.json | grep -o '"version": "[^"]*"' | cut -d'"' -f4)
            echo "Current TypeScript version: $CURRENT_VERSION"
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No existing TypeScript installation found"
            echo "current_version=0.0.0" >> $GITHUB_OUTPUT
          fi
          
      - name: Get latest TypeScript version from npm
        id: latest-version
        run: |
            # get latest tag
            LATEST_VERSION=$(npm view typescript dist-tags.latest)
            
            # ignore dev versions
            if [[ $LATEST_VERSION == *"dev"* ]]; then
              echo "Latest version $LATEST_VERSION contains 'dev', skipping update"
              echo "latest_version=${{ steps.current-version.outputs.current_version }}" >> $GITHUB_OUTPUT
            else
              echo "Latest TypeScript version: $LATEST_VERSION"
              echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            fi

      - name: Determine if update is needed
        id: update-needed
        run: |
            CURRENT_BASE_VERSION=$(echo "${{ steps.current-version.outputs.current_version }}" | sed 's/-hotfix\.[0-9]*$//')
            LATEST_VERSION="${{ steps.latest-version.outputs.latest_version }}"
            
            if [ "$CURRENT_BASE_VERSION" != "$LATEST_VERSION" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            elif [ "${{ inputs.force_release }}" == "true" ]; then
            # Get current suffix number if exists
            if [[ "${{ steps.current-version.outputs.current_version }}" =~ -hotfix\.([0-9]+)$ ]]; then
                CURRENT_SUFFIX="${BASH_REMATCH[1]}"
                NEW_SUFFIX=$((CURRENT_SUFFIX + 1))
            else
                NEW_SUFFIX=1
            fi
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$CURRENT_BASE_VERSION-hotfix.$NEW_SUFFIX" >> $GITHUB_OUTPUT
            else
            echo "update_needed=false" >> $GITHUB_OUTPUT
            echo "new_version=${{ steps.current-version.outputs.current_version }}" >> $GITHUB_OUTPUT
            fi
          
      - name: Install dos2unix
        if: steps.update-needed.outputs.update_needed == 'true'
        run: sudo apt-get install -y dos2unix
    
      - name: Compare versions and update if needed
        if: steps.update-needed.outputs.update_needed == 'true'
        run: |
            # backup extra files
            mkdir -p ./temp_backup
            cp ./BlazingTs/BlazingTs/tools/typescript/tsc2.cmd ./temp_backup/ || true
            cp ./BlazingTs/BlazingTs/tools/typescript/tsc3.cmd ./temp_backup/ || true
            cp ./BlazingTs/BlazingTs/tools/typescript/tsc2.sh ./temp_backup/ || true
            cp ./BlazingTs/BlazingTs/tools/typescript/tsc3.sh ./temp_backup/ || true
            
            # Install new version
            mkdir -p ./BlazingTs/BlazingTs/tools/typescript
            rm -rf ./BlazingTs/BlazingTs/tools/typescript/*
            npm install --prefix ./temp typescript@${{ steps.latest-version.outputs.latest_version }}
            mv ./temp/node_modules/typescript/* ./BlazingTs/BlazingTs/tools/typescript/
            
            # Restore backup files
            cp ./temp_backup/tsc2.cmd ./BlazingTs/BlazingTs/tools/typescript/ || true
            cp ./temp_backup/tsc3.cmd ./BlazingTs/BlazingTs/tools/typescript/ || true
            cp ./temp_backup/tsc2.sh ./BlazingTs/BlazingTs/tools/typescript/ || true
            cp ./temp_backup/tsc3.sh ./BlazingTs/BlazingTs/tools/typescript/ || true
            
            # Ensure shell scripts have correct permissions
            chmod +x ./BlazingTs/BlazingTs/tools/typescript/tsc2.sh || true
            chmod +x ./BlazingTs/BlazingTs/tools/typescript/tsc3.sh || true
            
            # Ensure shell scripts have Unix line endings
            dos2unix ./BlazingTs/BlazingTs/tools/typescript/tsc2.sh || true
            dos2unix ./BlazingTs/BlazingTs/tools/typescript/tsc3.sh || true
            
            # Cleanup
            rm -rf ./temp
            rm -rf ./temp_backup
          
      - name: Update project version
        if: steps.update-needed.outputs.update_needed == 'true'
        run: |
          sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.update-needed.outputs.new_version }}<\/Version>/" ./BlazingTs/BlazingTs/BlazingTs.csproj

      - name: Build NuGet package
        if: steps.update-needed.outputs.update_needed == 'true'
        working-directory: ./BlazingTs/BlazingTs
        run: |
          dotnet restore
          dotnet build --configuration Release /p:TargetFramework=netstandard2.0
          dotnet pack --configuration Release /p:TargetFramework=netstandard2.0 --no-build
          
      - name: Create GitHub Release
        if: steps.update-needed.outputs.update_needed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.update-needed.outputs.new_version }}
          release_name: Release v${{ steps.update-needed.outputs.new_version }}
          body: |
            Updated TypeScript from v${{ steps.current-version.outputs.current_version }} to v${{ steps.update-needed.outputs.new_version }}
            
            Target Framework: .NET Standard 2.0
          draft: false
          prerelease: false
          
      - name: Push to NuGet
        if: steps.update-needed.outputs.update_needed == 'true'
        working-directory: ./BlazingTs/BlazingTs
        run: |
          echo "Contents of ./bin/Release directory:"
          ls -la ./bin/Release/
          echo "Pushing new package version ${{ steps.update-needed.outputs.new_version }}"
          dotnet nuget push ./bin/Release/BlazingTs.${{ steps.update-needed.outputs.new_version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
  
      - name: Commit changes
        if: steps.update-needed.outputs.update_needed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./BlazingTs/BlazingTs/tools/typescript
          git add ./BlazingTs/BlazingTs/BlazingTs.csproj
          git commit -m "Update TypeScript to v${{ steps.update-needed.outputs.new_version }}"
          git push